package com.github.mrshan23.pytestguard.llm


import com.github.mrshan23.pytestguard.actions.controllers.TestGenerationController
import com.github.mrshan23.pytestguard.bundles.plugin.PluginMessagesBundle
import com.github.mrshan23.pytestguard.data.Report
import com.github.mrshan23.pytestguard.data.TestCase
import com.github.mrshan23.pytestguard.display.PyTestGuardDisplayManager
import com.github.mrshan23.pytestguard.display.custom.CustomProgressIndicator
import com.github.mrshan23.pytestguard.psi.PsiHelper
import com.github.mrshan23.pytestguard.test.TestAssembler
import com.github.mrshan23.pytestguard.test.TestFramework
import com.github.mrshan23.pytestguard.utils.createErrorNotification
import com.github.mrshan23.pytestguard.utils.isProcessStopped
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.progress.ProgressIndicator
import com.intellij.openapi.progress.ProgressManager
import com.intellij.openapi.progress.Task
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.VirtualFileManager


class Llm(private val project: Project) {

    private var report : Report? = null

    fun generateTestsForMethod(
        psiHelper: PsiHelper,
        caretOffset: Int,
        testFramework: TestFramework,
        testGenerationController: TestGenerationController,
        pyTestGuardDisplayManager: PyTestGuardDisplayManager,
    ) {
        testGenerationController.errorMonitor.clear()
        pyTestGuardDisplayManager.clear()

        ProgressManager.getInstance()
            .run(object : Task.Backgroundable(project, PluginMessagesBundle.get("testGenerationMessage")) {
                override fun run(indicator: ProgressIndicator) {
                    try {
                        val customProgressIndicator = CustomProgressIndicator(indicator)
                        testGenerationController.indicator = customProgressIndicator

                        if (isProcessStopped(testGenerationController.errorMonitor, customProgressIndicator)) return

                        var methodName: String? = null
                        ApplicationManager.getApplication().runReadAction {
                            val method = psiHelper.getFunctionForGeneration(caretOffset)
                                ?: run {
                                    testGenerationController.errorMonitor.notifyErrorOccurrence()
                                    return@runReadAction
                                }
                            methodName = method.name
                        }

                        if (isProcessStopped(testGenerationController.errorMonitor, customProgressIndicator)) return

                        val testAssembler = TestAssembler(
                            testGenerationController.errorMonitor,
                            customProgressIndicator,
                            project
                        )

                        report = Report()

                        // Assemble test suite from gemini response
                        val generatedTestSuite = testAssembler.assembleTestSuite(methodName!!)
                        generatedTestSuite?.let {
                            addTestCasesToReport(report!!, it)
                            report!!.testFramework = testFramework
                        } ?: run {
                            testGenerationController.errorMonitor.notifyErrorOccurrence()

                            createErrorNotification(
                                PluginMessagesBundle.get("geminiErrorTitle"),
                                PluginMessagesBundle.get("geminiNoGenerationMessage"),
                                project
                            )

                            return
                        }

                        if (isProcessStopped(testGenerationController.errorMonitor, customProgressIndicator)) return

                        customProgressIndicator.stop()
                    } catch (e: RuntimeException) {
                        e.printStackTrace()
                    }
                }

                override fun onFinished() {
                    super.onFinished()
                    testGenerationController.finished()

                    if (testGenerationController.errorMonitor.hasErrorOccurred() || report == null) return

                    pyTestGuardDisplayManager.display(
                        report!!,
                        testFramework,
                        project,
                    )

                    VirtualFileManager.getInstance().syncRefresh()
                }

            })
    }

    /**
     * Records the generated test cases in the given report.
     *
     * @param report The report object to store the test cases in.
     * @param testCases The list of test cases generated by LLM.
     */
    private fun addTestCasesToReport(report: Report, testCases: List<TestCase>) {
        for ((index, test) in testCases.withIndex()) {
            test.id = index
            report.testCaseList[index] = test
        }
    }

}
